---
sudo: required
dist: trusty
language: generic

matrix:
  include:
    - env: ANSIBLE_VERSION=ppa:ansible/ansible
    - env: ANSIBLE_VERSION=ppa:ansible/ansible-1.9

before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-add-repository -y $ANSIBLE_VERSION
 - sudo apt-get -y update
 - sudo apt-get -y install ansible
 - ansible --version
 # We download the latest deploy stable tag
 - sudo ansible-galaxy install carlosbuenosvinos.ansistrano-deploy

script:
 - echo localhost > inventory
 - ansible-playbook -i inventory test/test.yml --syntax-check
 - ansible-playbook -i inventory --connection=local --sudo -v test/deploy.yml
 - ansible-playbook -i inventory --connection=local --sudo -v test/deploy.yml
 - ansible-playbook -i inventory --connection=local --sudo -v test/test.yml