- name: Get releases path
  command: echo "{{ deploy_to }}/{{ version_dir }}"
  register: releases_path

- name: Get number of releases
  shell: echo `ls {{ releases_path.stdout }} -1t | wc -l`
  register: versions_count

- name: Check if there is more than one release
  fail: msg="Could not rollback the code because there is no prior release"
  when: versions_count.stdout|int <= 1

- name: Get current release version
  shell: echo `ls {{ deploy_to }}/{{ version_dir }} -1t | head -n 1`
  register: current_release_version

- name: Get previous releases version
  shell: echo `ls {{ deploy_to }}/{{ version_dir }} -1t | head -n 2 | tail -n 1`
  register: previous_release_version

- name: Change web softlink from current release to previous one
  file: state=link path={{ deploy_to }}/{{ current_dir }} src={{ deploy_to }}/{{ version_dir }}/{{ previous_release_version.stdout }}
